styled component
ericgmoon/r2r-frontend-kma pull request #16
Opened 2021-02-13 14:34 UTC by m-lo

Convert to styled component (added comments about special cases, notably styling React Native Elements (vs. View / Text)
Added stories for Overlay
Fix ENV for React Native Storybook (include the env name in the babel config)
Rename a few variables

2021-02-13 14:36 UTC, m-lo commented on App.js
> +export default process.env["REACT_NATIVE_STORYBOOK"] ? StorybookUIRoot : App;
Not sure why dot access to env doesn't work for me

2021-02-16 04:15 UTC, ericgmoon commented on App.js
> +export default process.env["REACT_NATIVE_STORYBOOK"] ? StorybookUIRoot : App;
It worked fine for me, but based on the response by Jack Zhang [here](https://stackoverflow.com/questions/33117227/setting-environment-variable-in-react-native), I have a feeling that the dot notation only works in certain shell environments.

Let's just add a global ignore for the `dot-notation` rule in `.eslintrc` in root.

2021-02-16 04:16 UTC, ericgmoon commented
Could you please update the Snapshot tests after checking that they look fine using Storybooks?

2021-02-16 04:18 UTC, ericgmoon requested changes

2021-02-16 04:18 UTC, ericgmoon commented on babel.config.js
> +          include: ["REACT_NATIVE_STORYBOOK"],
I don't think we need this? What is the purpose of this addition?

2021-02-17 11:47 UTC, m-lo commented on App.js
> +export default process.env["REACT_NATIVE_STORYBOOK"] ? StorybookUIRoot : App;
can ignore just that line

2021-02-17 22:09 UTC, ericgmoon commented on App.js
> +export default process.env["REACT_NATIVE_STORYBOOK"] ? StorybookUIRoot : App;
This seems like a problem which would occur every time we use environment variables, so I think a global declaration would make more sense. Thoughts?

2021-02-17 22:50 UTC, ericgmoon commented on src/components/common/button/__snapshots__/test.js.snap
> -          "paddingRight": 20,
This doesn't seem right.

2021-02-17 23:04 UTC, ericgmoon approved these changes
Fixed a few bugs but otherwise looks great! :heavy_check_mark:

2021-02-17 23:19 UTC, merged