Kma 11 develop overlay
ericgmoon/r2r-frontend-kma pull request #9
Opened 2021-02-04 07:48 UTC by GeorgeKandamkolathy

Created overlay component with button, title, and close icon.

2021-02-04 09:51 UTC, ericgmoon requested changes
Looks mostly great! Refer to my comments for feedback, and tests should be added before the PR can be merged in.

2021-02-04 09:51 UTC, ericgmoon commented on src/packages/common/overlay/index.js
> +      <EOverlay isVisible={true} overlayStyle={styles.overlay} {...others}>
`isVisible` automatically defaults to `isVisible={true}`. This is what is causing the linter to fail.

2021-02-04 09:51 UTC, ericgmoon commented on src/packages/common/overlay/index.js
> +            <View style={{ height: 15, width: 25 }}>
Could we put this style in `styles.js`?

2021-02-04 09:51 UTC, ericgmoon commented on src/packages/common/overlay/styles.js
> +    height: 25,
Should ideally be a multiple of 4 @m-lo

2021-02-04 12:01 UTC, nzh20 commented on src/packages/common/overlay/index.js
> +    <ThemeProvider>
Why do we have theme provider but no theme prop passed in? Is it being used here then?

2021-02-05 00:49 UTC, ericgmoon commented on src/packages/common/overlay/index.js
> +    <ThemeProvider>
It is not - I don't believe we need it. I agree it should be removed.

2021-02-11 01:18 UTC, ericgmoon requested changes

2021-02-11 01:18 UTC, ericgmoon commented on package.json
>      "react-native-vector-icons": "^8.0.0",
Let's get rid of all changes to `package.json` past line 29.

2021-02-11 01:18 UTC, ericgmoon commented on src/packages/common/overlay/index.js
> +
Get rid of newline here

2021-02-11 01:24 UTC, ericgmoon approved these changes
Great work! I have checked the visual renders on this manually and it looks good :)

We may need to update it so that the number of actions buttons is customisable, but happy to merge for now.

2021-02-11 01:26 UTC, merged